# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 11:12
from __future__ import unicode_literals

import accounts.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscription_end'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', accounts.models.AccountUserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_end',
        ),
    ]
